name: Code Quality Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Codacy Analysis
        env:
          CODACY_PROJECT_TOKEN: ${{ 80810084935147008386c41092c985e3 }}
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash -s report \
            -r coverage.xml
